import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, Download, Eye, Search, Trash2, Users, UserRoundPlus, WalletCards } from "lucide-react";
import { toast } from "sonner";
import ReceiptDialog from "@/components/ReceiptDialog";
import { api, currency, dateTime } from "@/lib/api";

export default function AdminPortal({ vendors, employees, refreshKey, onDataChange }) {
  const [dashboard, setDashboard] = useState(null);
  const [collections, setCollections] = useState([]);
  const [expenses, setExpenses] = useState([]);
  const [search, setSearch] = useState("");
  const [mode, setMode] = useState("All");
  const [receipt, setReceipt] = useState(null);
  const [vendorForm, setVendorForm] = useState({ name: "", business_name: "", phone: "", address: "" });
  const [employeeForm, setEmployeeForm] = useState({ name: "", phone: "", territory: "" });
  const [showVendorForm, setShowVendorForm] = useState(false);
  const [showEmployeeForm, setShowEmployeeForm] = useState(false);

  useEffect(() => {
    Promise.all([api.get("/dashboard"), api.get("/collections"), api.get("/expenses")]).then(([dash, col, exp]) => {
      setDashboard(dash.data);
      setCollections(col.data);
      setExpenses(exp.data);
    });
  }, [refreshKey]);

  const displayedCollections = useMemo(() => collections.filter((item) => (mode === "All" || item.payment_mode === mode) && `${item.vendor_name} ${item.employee_name}`.toLowerCase().includes(search.toLowerCase())), [collections, search, mode]);

  const createVendor = async (event) => { event.preventDefault(); await api.post("/vendors", vendorForm); setVendorForm({ name: "", business_name: "", phone: "", address: "" }); setShowVendorForm(false); toast.success("Vendor added"); onDataChange(); };
  const createEmployee = async (event) => { event.preventDefault(); await api.post("/employees", employeeForm); setEmployeeForm({ name: "", phone: "", territory: "" }); setShowEmployeeForm(false); toast.success("Field employee added"); onDataChange(); };
  const removeVendor = async (id) => { await api.delete(`/vendors/${id}`); toast.success("Vendor removed"); onDataChange(); };
  const exportCsv = () => { const rows = [["Receipt", "Date & Time", "Vendor", "Employee", "Amount", "Mode"], ...displayedCollections.map((item) => [item.receipt_number, dateTime(item.created_at), item.vendor_name, item.employee_name, item.amount, item.payment_mode])]; const blob = new Blob([rows.map((row) => row.join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "ledgerflow-collections.csv"; link.click(); URL.revokeObjectURL(url); };

  return <main className="admin-page" data-testid="admin-portal"><div className="admin-intro"><div><p className="eyebrow">CONTROL CENTER · LIVE</p><h1>Collection overview</h1><p>Track the field, reconcile faster, and keep every payment visible.</p></div><button className="outline-button" data-testid="export-collections-button" onClick={exportCsv}><Download size={17} /> Export CSV</button></div>
    <section className="metric-grid admin-metrics"><article className="metric-card ink" data-testid="admin-today-collection"><WalletCards /><span>Total collected today</span><strong>{currency(dashboard?.today_collection)}</strong><small>Across all active routes</small></article><article className="metric-card" data-testid="admin-monthly-collection"><BarChart3 /><span>Monthly aggregate</span><strong>{currency(dashboard?.monthly_collection)}</strong><small>Current calendar month</small></article><article className="metric-card" data-testid="admin-active-vendors"><Users /><span>Active vendors</span><strong>{dashboard?.active_vendors || 0}</strong><small>Master vendor list</small></article><article className="metric-card" data-testid="admin-active-employees"><UserRoundPlus /><span>Field employees</span><strong>{dashboard?.active_employees || 0}</strong><small>Active collection staff</small></article></section>
    <section className="chart-section"><div className="section-heading"><div><p className="eyebrow">7-DAY PULSE</p><h2>Collections trend</h2></div><b data-testid="admin-expense-total">Today&apos;s expenses · {currency(dashboard?.today_expenses)}</b></div><div className="chart-wrap" data-testid="collection-trend-chart"><ResponsiveContainer height={260} width="100%"><AreaChart data={dashboard?.trend || []}><defs><linearGradient id="collectionArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#059669" stopOpacity={0.28} /><stop offset="100%" stopColor="#059669" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#e2e8f0" vertical={false} /><XAxis dataKey="date" tickLine={false} axisLine={false} /><YAxis tickFormatter={(value) => `₹${value / 1000}k`} tickLine={false} axisLine={false} /><Tooltip formatter={(value) => currency(value)} /><Area dataKey="amount" stroke="#059669" strokeWidth={3} fill="url(#collectionArea)" /></AreaChart></ResponsiveContainer></div></section>
    <section className="admin-table-section" data-testid="live-collection-feed"><div className="section-heading"><div><p className="eyebrow">LIVE REGISTER</p><h2>Collections feed</h2></div><span className="live-pill">Live</span></div><div className="toolbar"><div className="search-field"><Search size={17} /><input data-testid="collection-search-input" placeholder="Find vendor or employee" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select data-testid="collection-mode-filter" value={mode} onChange={(event) => setMode(event.target.value)}>{["All", "Cash", "UPI", "Bank Transfer", "Cheque"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>Date & time</th><th>Vendor</th><th>Collected by</th><th>Mode</th><th>Amount</th><th>Receipt</th></tr></thead><tbody>{displayedCollections.map((item) => <tr data-testid={`admin-collection-${item.id}`} key={item.id}><td>{dateTime(item.created_at)}</td><td><strong>{item.vendor_name}</strong></td><td>{item.employee_name}</td><td><span className="mode-badge">{item.payment_mode}</span></td><td><b>{currency(item.amount)}</b></td><td><button aria-label={`View receipt ${item.receipt_number}`} className="table-icon-button" data-testid={`view-receipt-${item.id}`} onClick={() => setReceipt(item)}><Eye size={17} /></button></td></tr>)}</tbody></table></div></section>
    <section className="management-grid"><section className="management-section"><div className="section-heading"><div><p className="eyebrow">DIRECTORY</p><h2>Vendor management</h2></div><button className="compact-button" data-testid="toggle-vendor-form-button" onClick={() => setShowVendorForm(!showVendorForm)}>Add vendor</button></div>{showVendorForm && <form className="management-form" data-testid="vendor-form" onSubmit={createVendor}>{[["name", "Contact name"], ["business_name", "Business name"], ["phone", "WhatsApp number"], ["address", "Address"]].map(([key, label]) => <input required data-testid={`vendor-${key}-input`} key={key} placeholder={label} value={vendorForm[key]} onChange={(event) => setVendorForm({ ...vendorForm, [key]: event.target.value })} />)}<button className="primary-button" data-testid="vendor-submit-button" type="submit">Save vendor</button></form>}<div className="directory-list">{vendors.map((item) => <article data-testid={`vendor-${item.id}`} key={item.id}><div><strong>{item.business_name}</strong><span>{item.name} · {item.phone}</span></div><button aria-label={`Remove ${item.business_name}`} className="table-icon-button danger" data-testid={`remove-vendor-${item.id}`} onClick={() => removeVendor(item.id)}><Trash2 size={16} /></button></article>)}</div></section>
      <section className="management-section"><div className="section-heading"><div><p className="eyebrow">TEAM</p><h2>Field employees</h2></div><button className="compact-button" data-testid="toggle-employee-form-button" onClick={() => setShowEmployeeForm(!showEmployeeForm)}>Add employee</button></div>{showEmployeeForm && <form className="management-form" data-testid="employee-form" onSubmit={createEmployee}>{[["name", "Full name"], ["phone", "Phone number"], ["territory", "Territory"]].map(([key, label]) => <input required data-testid={`employee-${key}-input`} key={key} placeholder={label} value={employeeForm[key]} onChange={(event) => setEmployeeForm({ ...employeeForm, [key]: event.target.value })} />)}<button className="primary-button" data-testid="employee-submit-button" type="submit">Save employee</button></form>}<div className="directory-list">{employees.map((item) => <article data-testid={`employee-${item.id}`} key={item.id}><div className="person-cell">{item.avatar ? <img alt="" src={item.avatar} /> : <span className="avatar-fallback">{item.name[0]}</span>}<div><strong>{item.name}</strong><span>{item.territory} · {item.phone}</span></div></div></article>)}</div></section></section>
    <section className="admin-table-section expense-audit" data-testid="expense-audit-table"><div className="section-heading"><div><p className="eyebrow">AUDIT</p><h2>Daily employee expenses</h2></div></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Employee</th><th>Category</th><th>Remarks</th><th>Amount</th></tr></thead><tbody>{expenses.map((item) => <tr data-testid={`admin-expense-${item.id}`} key={item.id}><td>{item.date}</td><td>{item.employee_name}</td><td>{item.category}</td><td>{item.remarks}</td><td><b>{currency(item.amount)}</b></td></tr>)}</tbody></table></div></section><ReceiptDialog receipt={receipt} onClose={() => setReceipt(null)} /></main>;
}